version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  server:
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      depends_on:
        - database
      networks:
        - default
      ports:
      - "8080:8080"
  volumes:
    data:
